force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>Cart-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Package_Relationship__c/Cart_Package_Relationship__c.object-meta.xml
<CustomObject>
    <label>Cart Package Relationship</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>CartPackageRelationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Package Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Package_Relationship__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipName>CartPackageRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart_Package_Relationship__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>CartPackageRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart_Product_Relationship__c/Cart_Product_Relationship__c.object-meta.xml
<CustomObject>
    <label>Cart Product Relationship</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Product Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Product_Relationship__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Cart Product Relationships</relationshipLabel>
    <relationshipName>Cart_Product_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart_Product_Relationship__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Cart Product Relationships</relationshipLabel>
    <relationshipName>Cart_Product_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductXPackage__c/ProductXPackage__c.object-meta.xml
<CustomObject>
    <label>Product Package Relationship</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Package Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductXPackage__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Product Package Relationships</relationshipLabel>
    <relationshipName>Product_Package_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProductXPackage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Package Relationships</relationshipLabel>
    <relationshipName>Product_Package_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CartPackageRelationshipModel.cls
public with sharing class CartPackageRelationshipModel {
	public static void createProductCartRelationships(List<Cart_Package_Relationship__c> packageCartRelationships){
		Set<Id> packageIds = new Set<Id>();
		for(Cart_Package_Relationship__c cpr : packageCartRelationships) {
			if(!packageIds.contains(cpr.Package__c)) {
				packageIds.add(cpr.Package__c);
			}
		}

		if(!packageIds.isEmpty()) {
			List<Cart_Product_Relationship__c> cartProductList = new List<Cart_Product_Relationship__c>();

			Map<Id, Package__c> packageMap = new Map<Id, Package__c> ([SELECT Id,
			                                                           (SELECT Id,
                                                                        Product__c,
                                                                        Product__r.Price__c
			                                                            FROM Product_Package_Relationships__r)
			                                                           FROM Package__c
			                                                           WHERE Id IN: packageIds]);
            for(Cart_Package_Relationship__c cpr : packageCartRelationships) {
                
                for(ProductXPackage__c packageProduct : packagemap.get(cpr.Package__c).Product_Package_Relationships__r){
                    Cart_Product_Relationship__c cartProductInstance = new Cart_Product_Relationship__c();
                    cartProductInstance.Cart__c = cpr.Cart__c;
                    cartProductInstance.Quantity__c = 1;
                    cartProductInstance.Product__c = packageProduct.Product__c;
                    cartProductList.add(cartProductInstance);
                }
 
                
            }
            if(!cartProductList.isEmpty()){
                insert cartProductList;
            }
		}
	}
}