force-app/main/default/objects/Cart_Product_Relationship__c/Cart_Product_Relationship__c.object-meta.xml
<CustomObject>
    <label>Cart Product Relationship</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Product Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Product_Relationship__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Cart Product Relationships</relationshipLabel>
    <relationshipName>Cart_Product_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart_Product_Relationship__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CartProductRelationshipModel.cls
public with sharing class CartProductRelationshipModel {
    public static void setPrice(List<Cart_Product_Relationship__c> itemsNeedingPrice){
        Set<Id> productIds = new Set<Id>();
        for(Cart_Product_Relationship__c item : itemsNeedingPrice){
            if(!productIds.contains(item.Product__c)){
                productIds.add(item.Product__c);
            }
        }

        if(!productIds.isEmpty()){
            Map<Id, Product__c> productMap = new Map<Id, Product__c> ([SELECT Id, Price__c FROM Product__c WHERE Id IN: productIds]);

            for(Cart_Product_Relationship__c item : itemsNeedingPrice){
                item.Price__c = productMap.get(item.Product__c).Price__c;
            }
        }
    }


    public static void updateItemTotal(List<Cart_Product_Relationship__c> itemsToUpdate){
        for(Cart_Product_Relationship__c item : itemsToUpdate){
            item.Total__c = item.Price__c * item.Quantity__c;
        }
    }
}